language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '10'

stages:
  - 'Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Basic Tests'
    - stage: 'Deploy'
      name: 'Publish'
      script: yarn semantic-release

script: yarn test:ci
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
